global:
  scrape_interval: 15s  # Set the scrape interval to 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus self-monitoring

  - job_name: 'flask_svd'
    static_configs:
      - targets: ['localhost:5000']